import {
  DailyChallengeConfigSnapshot,
  DailyChallengeTaskDefinition,
} from '../types/daily-challenge-config.types';
import { ChallengeMetric, ChallengeScope } from '../types/daily-challenge.types';

export const DAILY_CHALLENGE_TASKS = [
  {
    id: 'general_hero_damage',
    scope: ChallengeScope.PERSONAL_GENERAL,
    metric: ChallengeMetric.HERO_DAMAGE,
    target: 500000,
  },
  {
    id: 'general_physical_damage',
    scope: ChallengeScope.PERSONAL_GENERAL,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 300000,
  },
  {
    id: 'general_magical_damage',
    scope: ChallengeScope.PERSONAL_GENERAL,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 300000,
  },
  {
    id: 'general_pure_damage',
    scope: ChallengeScope.PERSONAL_GENERAL,
    metric: ChallengeMetric.PURE_DAMAGE,
    target: 100000,
  },
  {
    id: 'general_damage_taken',
    scope: ChallengeScope.PERSONAL_GENERAL,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 500000,
  },
  {
    id: 'general_healing',
    scope: ChallengeScope.PERSONAL_GENERAL,
    metric: ChallengeMetric.HEALING,
    target: 300000,
  },
  {
    id: 'general_kills',
    scope: ChallengeScope.PERSONAL_GENERAL,
    metric: ChallengeMetric.KILLS,
    target: 20,
  },
  {
    id: 'general_assists',
    scope: ChallengeScope.PERSONAL_GENERAL,
    metric: ChallengeMetric.ASSISTS,
    target: 30,
  },
  {
    id: 'general_last_hits',
    scope: ChallengeScope.PERSONAL_GENERAL,
    metric: ChallengeMetric.LAST_HITS,
    target: 100,
  },
  {
    id: 'general_tower_kills',
    scope: ChallengeScope.PERSONAL_GENERAL,
    metric: ChallengeMetric.TOWER_KILLS,
    target: 3,
  },
  {
    id: 'general_bot_kills',
    scope: ChallengeScope.PERSONAL_GENERAL,
    metric: ChallengeMetric.BOT_KILLS,
    target: 50,
  },
  {
    id: 'general_roshan_kills',
    scope: ChallengeScope.PERSONAL_GENERAL,
    metric: ChallengeMetric.ROSHAN_KILLS,
    target: 1,
  },
  {
    id: 'general_stun_duration',
    scope: ChallengeScope.PERSONAL_GENERAL,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 60000,
  },
  {
    id: 'general_slow_duration',
    scope: ChallengeScope.PERSONAL_GENERAL,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 120000,
  },
  {
    id: 'general_root_duration',
    scope: ChallengeScope.PERSONAL_GENERAL,
    metric: ChallengeMetric.ROOT_DURATION_MS,
    target: 60000,
  },
  {
    id: 'general_silence_duration',
    scope: ChallengeScope.PERSONAL_GENERAL,
    metric: ChallengeMetric.SILENCE_DURATION_MS,
    target: 45000,
  },
  {
    id: 'general_taunt_duration',
    scope: ChallengeScope.PERSONAL_GENERAL,
    metric: ChallengeMetric.TAUNT_DURATION_MS,
    target: 30000,
  },
  {
    id: 'general_break_duration',
    scope: ChallengeScope.PERSONAL_GENERAL,
    metric: ChallengeMetric.BREAK_DURATION_MS,
    target: 30000,
  },
  {
    id: 'general_debuff_duration',
    scope: ChallengeScope.PERSONAL_GENERAL,
    metric: ChallengeMetric.DEBUFF_DURATION_MS,
    target: 180000,
  },
  {
    id: 'hero_crystal_maiden_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 350000,
    heroName: 'npc_dota_hero_crystal_maiden',
  },
  {
    id: 'hero_crystal_maiden_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ROOT_DURATION_MS,
    target: 80000,
    heroName: 'npc_dota_hero_crystal_maiden',
  },
  {
    id: 'hero_crystal_maiden_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_crystal_maiden',
  },
  {
    id: 'hero_lina_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HERO_DAMAGE,
    target: 800000,
    heroName: 'npc_dota_hero_lina',
  },
  {
    id: 'hero_lina_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_lina',
  },
  {
    id: 'hero_lina_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_lina',
  },
  {
    id: 'hero_axe_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 700000,
    heroName: 'npc_dota_hero_axe',
  },
  {
    id: 'hero_axe_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.TAUNT_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_axe',
  },
  {
    id: 'hero_axe_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PURE_DAMAGE,
    target: 250000,
    heroName: 'npc_dota_hero_axe',
  },
  {
    id: 'hero_omniknight_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_omniknight',
  },
  {
    id: 'hero_omniknight_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 550000,
    heroName: 'npc_dota_hero_omniknight',
  },
  {
    id: 'hero_omniknight_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HERO_DAMAGE,
    target: 600000,
    heroName: 'npc_dota_hero_omniknight',
  },
  {
    id: 'hero_dazzle_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 120000,
    heroName: 'npc_dota_hero_dazzle',
  },
  {
    id: 'hero_dazzle_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DEBUFF_DURATION_MS,
    target: 350000,
    heroName: 'npc_dota_hero_dazzle',
  },
  {
    id: 'hero_dazzle_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 450000,
    heroName: 'npc_dota_hero_dazzle',
  },
  {
    id: 'hero_witch_doctor_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_witch_doctor',
  },
  {
    id: 'hero_witch_doctor_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 70000,
    heroName: 'npc_dota_hero_witch_doctor',
  },
  {
    id: 'hero_witch_doctor_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HERO_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_witch_doctor',
  },
  {
    id: 'hero_warlock_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 80000,
    heroName: 'npc_dota_hero_warlock',
  },
  {
    id: 'hero_warlock_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_warlock',
  },
  {
    id: 'hero_warlock_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 500000,
    heroName: 'npc_dota_hero_warlock',
  },
  {
    id: 'hero_lion_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 110000,
    heroName: 'npc_dota_hero_lion',
  },
  {
    id: 'hero_lion_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DEBUFF_DURATION_MS,
    target: 250000,
    heroName: 'npc_dota_hero_lion',
  },
  {
    id: 'hero_lion_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_lion',
  },
  {
    id: 'hero_shadow_shaman_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DEBUFF_DURATION_MS,
    target: 120000,
    heroName: 'npc_dota_hero_shadow_shaman',
  },
  {
    id: 'hero_shadow_shaman_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.TOWER_KILLS,
    target: 3,
    heroName: 'npc_dota_hero_shadow_shaman',
  },
  {
    id: 'hero_shadow_shaman_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 500000,
    heroName: 'npc_dota_hero_shadow_shaman',
  },
  {
    id: 'hero_sven_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 750000,
    heroName: 'npc_dota_hero_sven',
  },
  {
    id: 'hero_sven_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 80000,
    heroName: 'npc_dota_hero_sven',
  },
  {
    id: 'hero_sven_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 500000,
    heroName: 'npc_dota_hero_sven',
  },
  {
    id: 'hero_juggernaut_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_juggernaut',
  },
  {
    id: 'hero_juggernaut_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 350000,
    heroName: 'npc_dota_hero_juggernaut',
  },
  {
    id: 'hero_juggernaut_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 80000,
    heroName: 'npc_dota_hero_juggernaut',
  },
  {
    id: 'hero_sniper_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 800000,
    heroName: 'npc_dota_hero_sniper',
  },
  {
    id: 'hero_sniper_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 250000,
    heroName: 'npc_dota_hero_sniper',
  },
  {
    id: 'hero_sniper_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.BOT_KILLS,
    target: 50,
    heroName: 'npc_dota_hero_sniper',
  },
  {
    id: 'hero_zuus_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 750000,
    heroName: 'npc_dota_hero_zuus',
  },
  {
    id: 'hero_zuus_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HERO_DAMAGE,
    target: 900000,
    heroName: 'npc_dota_hero_zuus',
  },
  {
    id: 'hero_zuus_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 120,
    heroName: 'npc_dota_hero_zuus',
  },
  {
    id: 'hero_pudge_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PURE_DAMAGE,
    target: 250000,
    heroName: 'npc_dota_hero_pudge',
  },
  {
    id: 'hero_pudge_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DEBUFF_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_pudge',
  },
  {
    id: 'hero_pudge_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 750000,
    heroName: 'npc_dota_hero_pudge',
  },
  {
    id: 'hero_bristleback_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 850000,
    heroName: 'npc_dota_hero_bristleback',
  },
  {
    id: 'hero_bristleback_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_bristleback',
  },
  {
    id: 'hero_bristleback_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DEBUFF_DURATION_MS,
    target: 350000,
    heroName: 'npc_dota_hero_bristleback',
  },
  {
    id: 'hero_tidehunter_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 700000,
    heroName: 'npc_dota_hero_tidehunter',
  },
  {
    id: 'hero_tidehunter_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 100000,
    heroName: 'npc_dota_hero_tidehunter',
  },
  {
    id: 'hero_tidehunter_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DEBUFF_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_tidehunter',
  },
  {
    id: 'hero_centaur_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 800000,
    heroName: 'npc_dota_hero_centaur',
  },
  {
    id: 'hero_centaur_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_centaur',
  },
  {
    id: 'hero_centaur_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 600000,
    heroName: 'npc_dota_hero_centaur',
  },
  {
    id: 'hero_viper_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 600000,
    heroName: 'npc_dota_hero_viper',
  },
  {
    id: 'hero_viper_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 350000,
    heroName: 'npc_dota_hero_viper',
  },
  {
    id: 'hero_viper_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DEBUFF_DURATION_MS,
    target: 500000,
    heroName: 'npc_dota_hero_viper',
  },
  {
    id: 'hero_venomancer_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_venomancer',
  },
  {
    id: 'hero_venomancer_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 450000,
    heroName: 'npc_dota_hero_venomancer',
  },
  {
    id: 'hero_venomancer_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DEBUFF_DURATION_MS,
    target: 600000,
    heroName: 'npc_dota_hero_venomancer',
  },
  {
    id: 'hero_enigma_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DEBUFF_DURATION_MS,
    target: 100000,
    heroName: 'npc_dota_hero_enigma',
  },
  {
    id: 'hero_enigma_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PURE_DAMAGE,
    target: 250000,
    heroName: 'npc_dota_hero_enigma',
  },
  {
    id: 'hero_enigma_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HERO_DAMAGE,
    target: 650000,
    heroName: 'npc_dota_hero_enigma',
  },
  {
    id: 'hero_phoenix_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 600000,
    heroName: 'npc_dota_hero_phoenix',
  },
  {
    id: 'hero_phoenix_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 80000,
    heroName: 'npc_dota_hero_phoenix',
  },
  {
    id: 'hero_phoenix_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DEBUFF_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_phoenix',
  },
  {
    id: 'hero_dragon_knight_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 650000,
    heroName: 'npc_dota_hero_dragon_knight',
  },
  {
    id: 'hero_dragon_knight_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 80000,
    heroName: 'npc_dota_hero_dragon_knight',
  },
  {
    id: 'hero_dragon_knight_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 650000,
    heroName: 'npc_dota_hero_dragon_knight',
  },
  {
    id: 'hero_phantom_assassin_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 900000,
    heroName: 'npc_dota_hero_phantom_assassin',
  },
  {
    id: 'hero_phantom_assassin_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.BOT_KILLS,
    target: 60,
    heroName: 'npc_dota_hero_phantom_assassin',
  },
  {
    id: 'hero_phantom_assassin_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HERO_DAMAGE,
    target: 1000000,
    heroName: 'npc_dota_hero_phantom_assassin',
  },
  {
    id: 'hero_nevermore_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 600000,
    heroName: 'npc_dota_hero_nevermore',
  },
  {
    id: 'hero_nevermore_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_nevermore',
  },
  {
    id: 'hero_nevermore_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HERO_DAMAGE,
    target: 1000000,
    heroName: 'npc_dota_hero_nevermore',
  },
  {
    id: 'hero_necrolyte_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 600000,
    heroName: 'npc_dota_hero_necrolyte',
  },
  {
    id: 'hero_necrolyte_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_necrolyte',
  },
  {
    id: 'hero_necrolyte_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 550000,
    heroName: 'npc_dota_hero_necrolyte',
  },
  {
    id: 'hero_windrunner_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_windrunner',
  },
  {
    id: 'hero_windrunner_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 80000,
    heroName: 'npc_dota_hero_windrunner',
  },
  {
    id: 'hero_windrunner_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 250000,
    heroName: 'npc_dota_hero_windrunner',
  },
  {
    id: 'hero_kunkka_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 750000,
    heroName: 'npc_dota_hero_kunkka',
  },
  {
    id: 'hero_kunkka_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 80000,
    heroName: 'npc_dota_hero_kunkka',
  },
  {
    id: 'hero_kunkka_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 550000,
    heroName: 'npc_dota_hero_kunkka',
  },
  {
    id: 'hero_earthshaker_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 130000,
    heroName: 'npc_dota_hero_earthshaker',
  },
  {
    id: 'hero_earthshaker_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 600000,
    heroName: 'npc_dota_hero_earthshaker',
  },
  {
    id: 'hero_earthshaker_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HERO_DAMAGE,
    target: 750000,
    heroName: 'npc_dota_hero_earthshaker',
  },
  {
    id: 'hero_disruptor_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SILENCE_DURATION_MS,
    target: 120000,
    heroName: 'npc_dota_hero_disruptor',
  },
  {
    id: 'hero_disruptor_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DEBUFF_DURATION_MS,
    target: 350000,
    heroName: 'npc_dota_hero_disruptor',
  },
  {
    id: 'hero_disruptor_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 500000,
    heroName: 'npc_dota_hero_disruptor',
  },
  {
    id: 'hero_silencer_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SILENCE_DURATION_MS,
    target: 140000,
    heroName: 'npc_dota_hero_silencer',
  },
  {
    id: 'hero_silencer_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 450000,
    heroName: 'npc_dota_hero_silencer',
  },
  {
    id: 'hero_silencer_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HERO_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_silencer',
  },
  {
    id: 'hero_abaddon_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_abaddon',
  },
  {
    id: 'hero_abaddon_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_abaddon',
  },
  {
    id: 'hero_abaddon_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_abaddon',
  },
  {
    id: 'hero_alchemist_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_alchemist',
  },
  {
    id: 'hero_alchemist_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_alchemist',
  },
  {
    id: 'hero_alchemist_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_alchemist',
  },
  {
    id: 'hero_ancient_apparition_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_ancient_apparition',
  },
  {
    id: 'hero_ancient_apparition_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_ancient_apparition',
  },
  {
    id: 'hero_ancient_apparition_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_ancient_apparition',
  },
  {
    id: 'hero_antimage_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_antimage',
  },
  {
    id: 'hero_antimage_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_antimage',
  },
  {
    id: 'hero_antimage_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_antimage',
  },
  {
    id: 'hero_arc_warden_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_arc_warden',
  },
  {
    id: 'hero_arc_warden_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_arc_warden',
  },
  {
    id: 'hero_arc_warden_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_arc_warden',
  },
  {
    id: 'hero_bane_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_bane',
  },
  {
    id: 'hero_bane_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_bane',
  },
  {
    id: 'hero_bane_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 600000,
    heroName: 'npc_dota_hero_bane',
  },
  {
    id: 'hero_batrider_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_batrider',
  },
  {
    id: 'hero_batrider_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_batrider',
  },
  {
    id: 'hero_batrider_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HERO_DAMAGE,
    target: 800000,
    heroName: 'npc_dota_hero_batrider',
  },
  {
    id: 'hero_beastmaster_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ROOT_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_beastmaster',
  },
  {
    id: 'hero_beastmaster_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_beastmaster',
  },
  {
    id: 'hero_beastmaster_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_beastmaster',
  },
  {
    id: 'hero_bloodseeker_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SILENCE_DURATION_MS,
    target: 120000,
    heroName: 'npc_dota_hero_bloodseeker',
  },
  {
    id: 'hero_bloodseeker_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_bloodseeker',
  },
  {
    id: 'hero_bloodseeker_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_bloodseeker',
  },
  {
    id: 'hero_bounty_hunter_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_bounty_hunter',
  },
  {
    id: 'hero_bounty_hunter_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_bounty_hunter',
  },
  {
    id: 'hero_bounty_hunter_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.KILLS,
    target: 45,
    heroName: 'npc_dota_hero_bounty_hunter',
  },
  {
    id: 'hero_brewmaster_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_brewmaster',
  },
  {
    id: 'hero_brewmaster_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_brewmaster',
  },
  {
    id: 'hero_brewmaster_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_brewmaster',
  },
  {
    id: 'hero_broodmother_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_broodmother',
  },
  {
    id: 'hero_broodmother_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_broodmother',
  },
  {
    id: 'hero_broodmother_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 600000,
    heroName: 'npc_dota_hero_broodmother',
  },
  {
    id: 'hero_chaos_knight_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_chaos_knight',
  },
  {
    id: 'hero_chaos_knight_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_chaos_knight',
  },
  {
    id: 'hero_chaos_knight_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.TOWER_KILLS,
    target: 3,
    heroName: 'npc_dota_hero_chaos_knight',
  },
  {
    id: 'hero_chen_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_chen',
  },
  {
    id: 'hero_chen_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_chen',
  },
  {
    id: 'hero_chen_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_chen',
  },
  {
    id: 'hero_clinkz_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_clinkz',
  },
  {
    id: 'hero_clinkz_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_clinkz',
  },
  {
    id: 'hero_clinkz_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.TOWER_KILLS,
    target: 3,
    heroName: 'npc_dota_hero_clinkz',
  },
  {
    id: 'hero_rattletrap_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_rattletrap',
  },
  {
    id: 'hero_rattletrap_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_rattletrap',
  },
  {
    id: 'hero_rattletrap_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_rattletrap',
  },
  {
    id: 'hero_dark_seer_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_dark_seer',
  },
  {
    id: 'hero_dark_seer_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_dark_seer',
  },
  {
    id: 'hero_dark_seer_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_dark_seer',
  },
  {
    id: 'hero_dark_willow_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_dark_willow',
  },
  {
    id: 'hero_dark_willow_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_dark_willow',
  },
  {
    id: 'hero_dark_willow_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_dark_willow',
  },
  {
    id: 'hero_death_prophet_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SILENCE_DURATION_MS,
    target: 120000,
    heroName: 'npc_dota_hero_death_prophet',
  },
  {
    id: 'hero_death_prophet_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_death_prophet',
  },
  {
    id: 'hero_death_prophet_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_death_prophet',
  },
  {
    id: 'hero_doom_bringer_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_doom_bringer',
  },
  {
    id: 'hero_doom_bringer_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_doom_bringer',
  },
  {
    id: 'hero_doom_bringer_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_doom_bringer',
  },
  {
    id: 'hero_drow_ranger_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SILENCE_DURATION_MS,
    target: 120000,
    heroName: 'npc_dota_hero_drow_ranger',
  },
  {
    id: 'hero_drow_ranger_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_drow_ranger',
  },
  {
    id: 'hero_drow_ranger_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.TOWER_KILLS,
    target: 3,
    heroName: 'npc_dota_hero_drow_ranger',
  },
  {
    id: 'hero_earth_spirit_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_earth_spirit',
  },
  {
    id: 'hero_earth_spirit_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_earth_spirit',
  },
  {
    id: 'hero_earth_spirit_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 600000,
    heroName: 'npc_dota_hero_earth_spirit',
  },
  {
    id: 'hero_elder_titan_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_elder_titan',
  },
  {
    id: 'hero_elder_titan_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_elder_titan',
  },
  {
    id: 'hero_elder_titan_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 600000,
    heroName: 'npc_dota_hero_elder_titan',
  },
  {
    id: 'hero_ember_spirit_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_ember_spirit',
  },
  {
    id: 'hero_ember_spirit_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_ember_spirit',
  },
  {
    id: 'hero_ember_spirit_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_ember_spirit',
  },
  {
    id: 'hero_enchantress_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ROOT_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_enchantress',
  },
  {
    id: 'hero_enchantress_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_enchantress',
  },
  {
    id: 'hero_enchantress_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_enchantress',
  },
  {
    id: 'hero_faceless_void_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_faceless_void',
  },
  {
    id: 'hero_faceless_void_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_faceless_void',
  },
  {
    id: 'hero_faceless_void_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 600000,
    heroName: 'npc_dota_hero_faceless_void',
  },
  {
    id: 'hero_grimstroke_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_grimstroke',
  },
  {
    id: 'hero_grimstroke_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_grimstroke',
  },
  {
    id: 'hero_grimstroke_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_grimstroke',
  },
  {
    id: 'hero_gyrocopter_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_gyrocopter',
  },
  {
    id: 'hero_gyrocopter_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_gyrocopter',
  },
  {
    id: 'hero_gyrocopter_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_gyrocopter',
  },
  {
    id: 'hero_huskar_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_huskar',
  },
  {
    id: 'hero_huskar_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_huskar',
  },
  {
    id: 'hero_huskar_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_huskar',
  },
  {
    id: 'hero_invoker_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_invoker',
  },
  {
    id: 'hero_invoker_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_invoker',
  },
  {
    id: 'hero_invoker_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_invoker',
  },
  {
    id: 'hero_wisp_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_wisp',
  },
  {
    id: 'hero_wisp_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_wisp',
  },
  {
    id: 'hero_wisp_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_wisp',
  },
  {
    id: 'hero_jakiro_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_jakiro',
  },
  {
    id: 'hero_jakiro_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_jakiro',
  },
  {
    id: 'hero_jakiro_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_jakiro',
  },
  {
    id: 'hero_keeper_of_the_light_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_keeper_of_the_light',
  },
  {
    id: 'hero_keeper_of_the_light_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_keeper_of_the_light',
  },
  {
    id: 'hero_keeper_of_the_light_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_keeper_of_the_light',
  },
  {
    id: 'hero_legion_commander_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_legion_commander',
  },
  {
    id: 'hero_legion_commander_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_legion_commander',
  },
  {
    id: 'hero_legion_commander_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_legion_commander',
  },
  {
    id: 'hero_leshrac_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_leshrac',
  },
  {
    id: 'hero_leshrac_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_leshrac',
  },
  {
    id: 'hero_leshrac_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_leshrac',
  },
  {
    id: 'hero_lich_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_lich',
  },
  {
    id: 'hero_lich_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_lich',
  },
  {
    id: 'hero_lich_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_lich',
  },
  {
    id: 'hero_life_stealer_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_life_stealer',
  },
  {
    id: 'hero_life_stealer_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_life_stealer',
  },
  {
    id: 'hero_life_stealer_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 600000,
    heroName: 'npc_dota_hero_life_stealer',
  },
  {
    id: 'hero_lone_druid_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ROOT_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_lone_druid',
  },
  {
    id: 'hero_lone_druid_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_lone_druid',
  },
  {
    id: 'hero_lone_druid_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.TOWER_KILLS,
    target: 3,
    heroName: 'npc_dota_hero_lone_druid',
  },
  {
    id: 'hero_luna_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_luna',
  },
  {
    id: 'hero_luna_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_luna',
  },
  {
    id: 'hero_luna_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_luna',
  },
  {
    id: 'hero_lycan_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_lycan',
  },
  {
    id: 'hero_lycan_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_lycan',
  },
  {
    id: 'hero_lycan_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_lycan',
  },
  {
    id: 'hero_magnataur_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_magnataur',
  },
  {
    id: 'hero_magnataur_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_magnataur',
  },
  {
    id: 'hero_magnataur_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_magnataur',
  },
  {
    id: 'hero_mars_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_mars',
  },
  {
    id: 'hero_mars_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_mars',
  },
  {
    id: 'hero_mars_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_mars',
  },
  {
    id: 'hero_medusa_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_medusa',
  },
  {
    id: 'hero_medusa_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_medusa',
  },
  {
    id: 'hero_medusa_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 600000,
    heroName: 'npc_dota_hero_medusa',
  },
  {
    id: 'hero_meepo_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_meepo',
  },
  {
    id: 'hero_meepo_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_meepo',
  },
  {
    id: 'hero_meepo_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_meepo',
  },
  {
    id: 'hero_mirana_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_mirana',
  },
  {
    id: 'hero_mirana_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_mirana',
  },
  {
    id: 'hero_mirana_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_mirana',
  },
  {
    id: 'hero_morphling_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_morphling',
  },
  {
    id: 'hero_morphling_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_morphling',
  },
  {
    id: 'hero_morphling_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_morphling',
  },
  {
    id: 'hero_monkey_king_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_monkey_king',
  },
  {
    id: 'hero_monkey_king_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_monkey_king',
  },
  {
    id: 'hero_monkey_king_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_monkey_king',
  },
  {
    id: 'hero_naga_siren_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ROOT_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_naga_siren',
  },
  {
    id: 'hero_naga_siren_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_naga_siren',
  },
  {
    id: 'hero_naga_siren_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_naga_siren',
  },
  {
    id: 'hero_furion_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ROOT_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_furion',
  },
  {
    id: 'hero_furion_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_furion',
  },
  {
    id: 'hero_furion_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_furion',
  },
  {
    id: 'hero_night_stalker_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_night_stalker',
  },
  {
    id: 'hero_night_stalker_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_night_stalker',
  },
  {
    id: 'hero_night_stalker_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_night_stalker',
  },
  {
    id: 'hero_nyx_assassin_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_nyx_assassin',
  },
  {
    id: 'hero_nyx_assassin_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_nyx_assassin',
  },
  {
    id: 'hero_nyx_assassin_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_nyx_assassin',
  },
  {
    id: 'hero_ogre_magi_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_ogre_magi',
  },
  {
    id: 'hero_ogre_magi_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_ogre_magi',
  },
  {
    id: 'hero_ogre_magi_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 600000,
    heroName: 'npc_dota_hero_ogre_magi',
  },
  {
    id: 'hero_oracle_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_oracle',
  },
  {
    id: 'hero_oracle_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_oracle',
  },
  {
    id: 'hero_oracle_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_oracle',
  },
  {
    id: 'hero_obsidian_destroyer_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_obsidian_destroyer',
  },
  {
    id: 'hero_obsidian_destroyer_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_obsidian_destroyer',
  },
  {
    id: 'hero_obsidian_destroyer_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_obsidian_destroyer',
  },
  {
    id: 'hero_pangolier_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_pangolier',
  },
  {
    id: 'hero_pangolier_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_pangolier',
  },
  {
    id: 'hero_pangolier_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_pangolier',
  },
  {
    id: 'hero_phantom_lancer_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_phantom_lancer',
  },
  {
    id: 'hero_phantom_lancer_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_phantom_lancer',
  },
  {
    id: 'hero_phantom_lancer_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_phantom_lancer',
  },
  {
    id: 'hero_puck_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_puck',
  },
  {
    id: 'hero_puck_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_puck',
  },
  {
    id: 'hero_puck_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_puck',
  },
  {
    id: 'hero_pugna_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_pugna',
  },
  {
    id: 'hero_pugna_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_pugna',
  },
  {
    id: 'hero_pugna_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_pugna',
  },
  {
    id: 'hero_queenofpain_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_queenofpain',
  },
  {
    id: 'hero_queenofpain_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_queenofpain',
  },
  {
    id: 'hero_queenofpain_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_queenofpain',
  },
  {
    id: 'hero_razor_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_razor',
  },
  {
    id: 'hero_razor_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_razor',
  },
  {
    id: 'hero_razor_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_razor',
  },
  {
    id: 'hero_riki_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_riki',
  },
  {
    id: 'hero_riki_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_riki',
  },
  {
    id: 'hero_riki_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.KILLS,
    target: 45,
    heroName: 'npc_dota_hero_riki',
  },
  {
    id: 'hero_rubick_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_rubick',
  },
  {
    id: 'hero_rubick_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_rubick',
  },
  {
    id: 'hero_rubick_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_rubick',
  },
  {
    id: 'hero_sand_king_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_sand_king',
  },
  {
    id: 'hero_sand_king_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_sand_king',
  },
  {
    id: 'hero_sand_king_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_sand_king',
  },
  {
    id: 'hero_shadow_demon_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_shadow_demon',
  },
  {
    id: 'hero_shadow_demon_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_shadow_demon',
  },
  {
    id: 'hero_shadow_demon_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.KILLS,
    target: 45,
    heroName: 'npc_dota_hero_shadow_demon',
  },
  {
    id: 'hero_skywrath_mage_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_skywrath_mage',
  },
  {
    id: 'hero_skywrath_mage_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_skywrath_mage',
  },
  {
    id: 'hero_skywrath_mage_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_skywrath_mage',
  },
  {
    id: 'hero_slardar_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_slardar',
  },
  {
    id: 'hero_slardar_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_slardar',
  },
  {
    id: 'hero_slardar_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 600000,
    heroName: 'npc_dota_hero_slardar',
  },
  {
    id: 'hero_slark_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_slark',
  },
  {
    id: 'hero_slark_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_slark',
  },
  {
    id: 'hero_slark_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_slark',
  },
  {
    id: 'hero_snapfire_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_snapfire',
  },
  {
    id: 'hero_snapfire_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_snapfire',
  },
  {
    id: 'hero_snapfire_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_snapfire',
  },
  {
    id: 'hero_spectre_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_spectre',
  },
  {
    id: 'hero_spectre_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_spectre',
  },
  {
    id: 'hero_spectre_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 600000,
    heroName: 'npc_dota_hero_spectre',
  },
  {
    id: 'hero_spirit_breaker_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_spirit_breaker',
  },
  {
    id: 'hero_spirit_breaker_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_spirit_breaker',
  },
  {
    id: 'hero_spirit_breaker_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 600000,
    heroName: 'npc_dota_hero_spirit_breaker',
  },
  {
    id: 'hero_storm_spirit_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_storm_spirit',
  },
  {
    id: 'hero_storm_spirit_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_storm_spirit',
  },
  {
    id: 'hero_storm_spirit_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_storm_spirit',
  },
  {
    id: 'hero_techies_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_techies',
  },
  {
    id: 'hero_techies_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_techies',
  },
  {
    id: 'hero_techies_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_techies',
  },
  {
    id: 'hero_templar_assassin_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_templar_assassin',
  },
  {
    id: 'hero_templar_assassin_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_templar_assassin',
  },
  {
    id: 'hero_templar_assassin_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.KILLS,
    target: 45,
    heroName: 'npc_dota_hero_templar_assassin',
  },
  {
    id: 'hero_terrorblade_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_terrorblade',
  },
  {
    id: 'hero_terrorblade_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_terrorblade',
  },
  {
    id: 'hero_terrorblade_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_terrorblade',
  },
  {
    id: 'hero_shredder_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_shredder',
  },
  {
    id: 'hero_shredder_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_shredder',
  },
  {
    id: 'hero_shredder_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_shredder',
  },
  {
    id: 'hero_tinker_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_tinker',
  },
  {
    id: 'hero_tinker_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_tinker',
  },
  {
    id: 'hero_tinker_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_tinker',
  },
  {
    id: 'hero_tiny_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_tiny',
  },
  {
    id: 'hero_tiny_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_tiny',
  },
  {
    id: 'hero_tiny_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_tiny',
  },
  {
    id: 'hero_treant_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_treant',
  },
  {
    id: 'hero_treant_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_treant',
  },
  {
    id: 'hero_treant_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_treant',
  },
  {
    id: 'hero_troll_warlord_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_troll_warlord',
  },
  {
    id: 'hero_troll_warlord_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_troll_warlord',
  },
  {
    id: 'hero_troll_warlord_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.TOWER_KILLS,
    target: 3,
    heroName: 'npc_dota_hero_troll_warlord',
  },
  {
    id: 'hero_tusk_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_tusk',
  },
  {
    id: 'hero_tusk_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_tusk',
  },
  {
    id: 'hero_tusk_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_tusk',
  },
  {
    id: 'hero_abyssal_underlord_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_abyssal_underlord',
  },
  {
    id: 'hero_abyssal_underlord_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 600000,
    heroName: 'npc_dota_hero_abyssal_underlord',
  },
  {
    id: 'hero_abyssal_underlord_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_abyssal_underlord',
  },
  {
    id: 'hero_undying_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_undying',
  },
  {
    id: 'hero_undying_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_undying',
  },
  {
    id: 'hero_undying_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_undying',
  },
  {
    id: 'hero_ursa_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_ursa',
  },
  {
    id: 'hero_ursa_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_ursa',
  },
  {
    id: 'hero_ursa_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_ursa',
  },
  {
    id: 'hero_vengefulspirit_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_vengefulspirit',
  },
  {
    id: 'hero_vengefulspirit_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_vengefulspirit',
  },
  {
    id: 'hero_vengefulspirit_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_vengefulspirit',
  },
  {
    id: 'hero_visage_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_visage',
  },
  {
    id: 'hero_visage_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 600000,
    heroName: 'npc_dota_hero_visage',
  },
  {
    id: 'hero_visage_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.KILLS,
    target: 45,
    heroName: 'npc_dota_hero_visage',
  },
  {
    id: 'hero_void_spirit_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ROOT_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_void_spirit',
  },
  {
    id: 'hero_void_spirit_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_void_spirit',
  },
  {
    id: 'hero_void_spirit_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_void_spirit',
  },
  {
    id: 'hero_weaver_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SLOW_DURATION_MS,
    target: 300000,
    heroName: 'npc_dota_hero_weaver',
  },
  {
    id: 'hero_weaver_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_weaver',
  },
  {
    id: 'hero_weaver_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.KILLS,
    target: 45,
    heroName: 'npc_dota_hero_weaver',
  },
  {
    id: 'hero_winter_wyvern_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_winter_wyvern',
  },
  {
    id: 'hero_winter_wyvern_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_winter_wyvern',
  },
  {
    id: 'hero_winter_wyvern_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_winter_wyvern',
  },
  {
    id: 'hero_skeleton_king_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_skeleton_king',
  },
  {
    id: 'hero_skeleton_king_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_skeleton_king',
  },
  {
    id: 'hero_skeleton_king_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_skeleton_king',
  },
  {
    id: 'hero_hoodwink_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_hoodwink',
  },
  {
    id: 'hero_hoodwink_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_hoodwink',
  },
  {
    id: 'hero_hoodwink_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_hoodwink',
  },
  {
    id: 'hero_dawnbreaker_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_dawnbreaker',
  },
  {
    id: 'hero_dawnbreaker_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_dawnbreaker',
  },
  {
    id: 'hero_dawnbreaker_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_dawnbreaker',
  },
  {
    id: 'hero_marci_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_marci',
  },
  {
    id: 'hero_marci_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_marci',
  },
  {
    id: 'hero_marci_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_marci',
  },
  {
    id: 'hero_primal_beast_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_primal_beast',
  },
  {
    id: 'hero_primal_beast_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 600000,
    heroName: 'npc_dota_hero_primal_beast',
  },
  {
    id: 'hero_primal_beast_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.ASSISTS,
    target: 100,
    heroName: 'npc_dota_hero_primal_beast',
  },
  {
    id: 'hero_muerta_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.SILENCE_DURATION_MS,
    target: 120000,
    heroName: 'npc_dota_hero_muerta',
  },
  {
    id: 'hero_muerta_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_muerta',
  },
  {
    id: 'hero_muerta_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_muerta',
  },
  {
    id: 'hero_ringmaster_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_ringmaster',
  },
  {
    id: 'hero_ringmaster_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_ringmaster',
  },
  {
    id: 'hero_ringmaster_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_ringmaster',
  },
  {
    id: 'hero_kez_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_kez',
  },
  {
    id: 'hero_kez_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.HEALING,
    target: 100000,
    heroName: 'npc_dota_hero_kez',
  },
  {
    id: 'hero_kez_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.PHYSICAL_DAMAGE,
    target: 700000,
    heroName: 'npc_dota_hero_kez',
  },
  {
    id: 'hero_largo_1',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.STUN_DURATION_MS,
    target: 90000,
    heroName: 'npc_dota_hero_largo',
  },
  {
    id: 'hero_largo_2',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.MAGICAL_DAMAGE,
    target: 550000,
    heroName: 'npc_dota_hero_largo',
  },
  {
    id: 'hero_largo_3',
    scope: ChallengeScope.PERSONAL_HERO,
    metric: ChallengeMetric.DAMAGE_TAKEN,
    target: 600000,
    heroName: 'npc_dota_hero_largo',
  },
  {
    id: 'global_bot_kills',
    scope: ChallengeScope.GLOBAL,
    metric: ChallengeMetric.BOT_KILLS,
    target: 10000,
  },
  {
    id: 'global_roshan_kills',
    scope: ChallengeScope.GLOBAL,
    metric: ChallengeMetric.ROSHAN_KILLS,
    target: 200,
  },
  {
    id: 'global_tower_kills',
    scope: ChallengeScope.GLOBAL,
    metric: ChallengeMetric.TOWER_KILLS,
    target: 1500,
  },
  {
    id: 'global_hero_damage',
    scope: ChallengeScope.GLOBAL,
    metric: ChallengeMetric.HERO_DAMAGE,
    target: 100000000,
  },
] satisfies DailyChallengeTaskDefinition[];

export const DAILY_CHALLENGE_CONFIG = {
  id: 'daily-challenge-v1',
  version: 1,
  personalRoundsPerDay: 3,
  personalStarRewards: { 1: 80, 2: 100, 3: 120 },
  personalStarWeights: { 1: 1, 2: 1, 3: 1 },
  personalDefaultStarMultipliers: { 1: 0.75, 2: 1, 3: 1.5 },
  tasks: DAILY_CHALLENGE_TASKS,
  globalRewardTiers: {
    topPercent: 10,
    middlePercent: 30,
    topRewardSeasonPoint: 100,
    middleRewardSeasonPoint: 90,
    baseRewardSeasonPoint: 80,
  },
  refreshCostsMemberPoint: [10, 20, 30, 50, 50],
  streakMilestones: [
    { days: 3, rewardSeasonPoint: 50 },
    { days: 7, rewardSeasonPoint: 120 },
    { days: 14, rewardSeasonPoint: 300 },
    { days: 30, rewardSeasonPoint: 800 },
  ],
} satisfies DailyChallengeConfigSnapshot;
