import { TaskMetric, TaskScope } from '../types/daily-task.types';

export interface TaskDefinition {
  id: string;
  scope: TaskScope;
  metric: TaskMetric;
  /** 1-star base target. */
  target: number;
  heroName?: string;
}

export const ROUNDS_PER_DAY = 3;
export const STAR_REWARDS = { 1: 60, 2: 80, 3: 100 } as const;
export const STAR_TARGET_MULTIPLIERS = { 1: 1, 2: 1.5, 3: 2 } as const;
export const SMALL_TARGET_THRESHOLD = 10;

export const DAILY_TASKS: TaskDefinition[] = [
  { id: 'general_kills', scope: TaskScope.PERSONAL_GENERAL, metric: TaskMetric.KILLS, target: 60 },
  {
    id: 'general_assists',
    scope: TaskScope.PERSONAL_GENERAL,
    metric: TaskMetric.ASSISTS,
    target: 40,
  },
  {
    id: 'general_last_hits',
    scope: TaskScope.PERSONAL_GENERAL,
    metric: TaskMetric.LAST_HITS,
    target: 200,
  },
  {
    id: 'general_tower_kills',
    scope: TaskScope.PERSONAL_GENERAL,
    metric: TaskMetric.TOWER_KILLS,
    target: 4,
  },
  {
    id: 'general_hero_damage',
    scope: TaskScope.PERSONAL_GENERAL,
    metric: TaskMetric.HERO_DAMAGE,
    target: 1_000_000,
  },
  {
    id: 'general_healing',
    scope: TaskScope.PERSONAL_GENERAL,
    metric: TaskMetric.HEALING,
    target: 40_000,
  },
  {
    id: 'general_total_gold_earned',
    scope: TaskScope.PERSONAL_GENERAL,
    metric: TaskMetric.TOTAL_GOLD_EARNED,
    target: 160_000,
  },
  {
    id: 'general_damage_taken',
    scope: TaskScope.PERSONAL_GENERAL,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 200_000,
  },
  {
    id: 'general_stun_duration',
    scope: TaskScope.PERSONAL_GENERAL,
    metric: TaskMetric.STUN_DURATION,
    target: 100,
  },
  {
    id: 'general_roshan_kills',
    scope: TaskScope.PERSONAL_GENERAL,
    metric: TaskMetric.ROSHAN_KILLS,
    target: 1,
  },
  {
    id: 'hero_crystal_maiden_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 70,
    heroName: 'npc_dota_hero_crystal_maiden',
  },
  {
    id: 'hero_crystal_maiden_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 30,
    heroName: 'npc_dota_hero_crystal_maiden',
  },
  {
    id: 'hero_lina_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 550_000,
    heroName: 'npc_dota_hero_lina',
  },
  {
    id: 'hero_lina_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 70,
    heroName: 'npc_dota_hero_lina',
  },
  {
    id: 'hero_axe_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 220_000,
    heroName: 'npc_dota_hero_axe',
  },
  {
    id: 'hero_axe_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 300_000,
    heroName: 'npc_dota_hero_axe',
  },
  {
    id: 'hero_omniknight_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HEALING,
    target: 40_000,
    heroName: 'npc_dota_hero_omniknight',
  },
  {
    id: 'hero_omniknight_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 180_000,
    heroName: 'npc_dota_hero_omniknight',
  },
  {
    id: 'hero_dazzle_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HEALING,
    target: 80_000,
    heroName: 'npc_dota_hero_dazzle',
  },
  {
    id: 'hero_dazzle_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 60,
    heroName: 'npc_dota_hero_dazzle',
  },
  {
    id: 'hero_witch_doctor_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HEALING,
    target: 30_000,
    heroName: 'npc_dota_hero_witch_doctor',
  },
  {
    id: 'hero_witch_doctor_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 80,
    heroName: 'npc_dota_hero_witch_doctor',
  },
  {
    id: 'hero_warlock_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HEALING,
    target: 30_000,
    heroName: 'npc_dota_hero_warlock',
  },
  {
    id: 'hero_warlock_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 320_000,
    heroName: 'npc_dota_hero_warlock',
  },
  {
    id: 'hero_lion_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 300,
    heroName: 'npc_dota_hero_lion',
  },
  {
    id: 'hero_lion_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 350_000,
    heroName: 'npc_dota_hero_lion',
  },
  {
    id: 'hero_shadow_shaman_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.TOWER_KILLS,
    target: 5,
    heroName: 'npc_dota_hero_shadow_shaman',
  },
  {
    id: 'hero_shadow_shaman_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 100,
    heroName: 'npc_dota_hero_shadow_shaman',
  },
  {
    id: 'hero_sven_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_sven',
  },
  {
    id: 'hero_sven_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 50,
    heroName: 'npc_dota_hero_sven',
  },
  {
    id: 'hero_juggernaut_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 480_000,
    heroName: 'npc_dota_hero_juggernaut',
  },
  {
    id: 'hero_sniper_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 600_000,
    heroName: 'npc_dota_hero_sniper',
  },
  {
    id: 'hero_sniper_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.KILLS,
    target: 40,
    heroName: 'npc_dota_hero_sniper',
  },
  {
    id: 'hero_zuus_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 900_000,
    heroName: 'npc_dota_hero_zuus',
  },
  {
    id: 'hero_zuus_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 70,
    heroName: 'npc_dota_hero_zuus',
  },
  {
    id: 'hero_pudge_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 300_000,
    heroName: 'npc_dota_hero_pudge',
  },
  {
    id: 'hero_pudge_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 220_000,
    heroName: 'npc_dota_hero_pudge',
  },
  {
    id: 'hero_bristleback_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 260_000,
    heroName: 'npc_dota_hero_bristleback',
  },
  {
    id: 'hero_bristleback_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_bristleback',
  },
  {
    id: 'hero_tidehunter_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 220_000,
    heroName: 'npc_dota_hero_tidehunter',
  },
  {
    id: 'hero_tidehunter_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 80,
    heroName: 'npc_dota_hero_tidehunter',
  },
  {
    id: 'hero_centaur_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 240_000,
    heroName: 'npc_dota_hero_centaur',
  },
  {
    id: 'hero_centaur_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 70,
    heroName: 'npc_dota_hero_centaur',
  },
  {
    id: 'hero_viper_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 480_000,
    heroName: 'npc_dota_hero_viper',
  },
  {
    id: 'hero_viper_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 200_000,
    heroName: 'npc_dota_hero_viper',
  },
  {
    id: 'hero_venomancer_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 350_000,
    heroName: 'npc_dota_hero_venomancer',
  },
  {
    id: 'hero_venomancer_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 50,
    heroName: 'npc_dota_hero_venomancer',
  },
  {
    id: 'hero_enigma_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 300_000,
    heroName: 'npc_dota_hero_enigma',
  },
  {
    id: 'hero_phoenix_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 350_000,
    heroName: 'npc_dota_hero_phoenix',
  },
  {
    id: 'hero_phoenix_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HEALING,
    target: 60_000,
    heroName: 'npc_dota_hero_phoenix',
  },
  {
    id: 'hero_dragon_knight_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 220_000,
    heroName: 'npc_dota_hero_dragon_knight',
  },
  {
    id: 'hero_dragon_knight_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 60,
    heroName: 'npc_dota_hero_dragon_knight',
  },
  {
    id: 'hero_phantom_assassin_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 600_000,
    heroName: 'npc_dota_hero_phantom_assassin',
  },
  {
    id: 'hero_phantom_assassin_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.KILLS,
    target: 50,
    heroName: 'npc_dota_hero_phantom_assassin',
  },
  {
    id: 'hero_nevermore_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 550_000,
    heroName: 'npc_dota_hero_nevermore',
  },
  {
    id: 'hero_nevermore_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.KILLS,
    target: 40,
    heroName: 'npc_dota_hero_nevermore',
  },
  {
    id: 'hero_necrolyte_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_necrolyte',
  },
  {
    id: 'hero_necrolyte_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HEALING,
    target: 20_000,
    heroName: 'npc_dota_hero_necrolyte',
  },
  {
    id: 'hero_windrunner_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_windrunner',
  },
  {
    id: 'hero_windrunner_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 30,
    heroName: 'npc_dota_hero_windrunner',
  },
  {
    id: 'hero_kunkka_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 90,
    heroName: 'npc_dota_hero_kunkka',
  },
  {
    id: 'hero_kunkka_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 200_000,
    heroName: 'npc_dota_hero_kunkka',
  },
  {
    id: 'hero_earthshaker_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 400,
    heroName: 'npc_dota_hero_earthshaker',
  },
  {
    id: 'hero_earthshaker_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 350_000,
    heroName: 'npc_dota_hero_earthshaker',
  },
  {
    id: 'hero_disruptor_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 70,
    heroName: 'npc_dota_hero_disruptor',
  },
  {
    id: 'hero_silencer_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_silencer',
  },
  {
    id: 'hero_silencer_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 50,
    heroName: 'npc_dota_hero_silencer',
  },
  {
    id: 'hero_abaddon_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HEALING,
    target: 20_000,
    heroName: 'npc_dota_hero_abaddon',
  },
  {
    id: 'hero_abaddon_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 480_000,
    heroName: 'npc_dota_hero_abaddon',
  },
  {
    id: 'hero_alchemist_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 60,
    heroName: 'npc_dota_hero_alchemist',
  },
  {
    id: 'hero_alchemist_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_alchemist',
  },
  {
    id: 'hero_ancient_apparition_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 60,
    heroName: 'npc_dota_hero_ancient_apparition',
  },
  {
    id: 'hero_ancient_apparition_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 50,
    heroName: 'npc_dota_hero_ancient_apparition',
  },
  {
    id: 'hero_antimage_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_antimage',
  },
  {
    id: 'hero_antimage_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.KILLS,
    target: 40,
    heroName: 'npc_dota_hero_antimage',
  },
  {
    id: 'hero_arc_warden_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 550_000,
    heroName: 'npc_dota_hero_arc_warden',
  },
  {
    id: 'hero_arc_warden_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.TOWER_KILLS,
    target: 5,
    heroName: 'npc_dota_hero_arc_warden',
  },
  {
    id: 'hero_bane_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 100,
    heroName: 'npc_dota_hero_bane',
  },
  {
    id: 'hero_bane_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 40,
    heroName: 'npc_dota_hero_bane',
  },
  {
    id: 'hero_batrider_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 40,
    heroName: 'npc_dota_hero_batrider',
  },
  {
    id: 'hero_batrider_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.TOWER_KILLS,
    target: 3,
    heroName: 'npc_dota_hero_batrider',
  },
  {
    id: 'hero_beastmaster_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 60,
    heroName: 'npc_dota_hero_beastmaster',
  },
  {
    id: 'hero_bloodseeker_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_bloodseeker',
  },
  {
    id: 'hero_bloodseeker_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.KILLS,
    target: 40,
    heroName: 'npc_dota_hero_bloodseeker',
  },
  {
    id: 'hero_bounty_hunter_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 400_000,
    heroName: 'npc_dota_hero_bounty_hunter',
  },
  {
    id: 'hero_bounty_hunter_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.KILLS,
    target: 36,
    heroName: 'npc_dota_hero_bounty_hunter',
  },
  {
    id: 'hero_brewmaster_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 50,
    heroName: 'npc_dota_hero_brewmaster',
  },
  {
    id: 'hero_brewmaster_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_brewmaster',
  },
  {
    id: 'hero_broodmother_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_broodmother',
  },
  {
    id: 'hero_broodmother_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 180_000,
    heroName: 'npc_dota_hero_broodmother',
  },
  {
    id: 'hero_chaos_knight_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 60,
    heroName: 'npc_dota_hero_chaos_knight',
  },
  {
    id: 'hero_chaos_knight_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.TOWER_KILLS,
    target: 4,
    heroName: 'npc_dota_hero_chaos_knight',
  },
  {
    id: 'hero_chen_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 40,
    heroName: 'npc_dota_hero_chen',
  },
  {
    id: 'hero_chen_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_chen',
  },
  {
    id: 'hero_clinkz_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 480_000,
    heroName: 'npc_dota_hero_clinkz',
  },
  {
    id: 'hero_clinkz_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.TOWER_KILLS,
    target: 4,
    heroName: 'npc_dota_hero_clinkz',
  },
  {
    id: 'hero_rattletrap_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 100,
    heroName: 'npc_dota_hero_rattletrap',
  },
  {
    id: 'hero_rattletrap_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 400_000,
    heroName: 'npc_dota_hero_rattletrap',
  },
  {
    id: 'hero_dark_seer_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 100,
    heroName: 'npc_dota_hero_dark_seer',
  },
  {
    id: 'hero_dark_seer_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_dark_seer',
  },
  {
    id: 'hero_dark_willow_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 350_000,
    heroName: 'npc_dota_hero_dark_willow',
  },
  {
    id: 'hero_dark_willow_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 30,
    heroName: 'npc_dota_hero_dark_willow',
  },
  {
    id: 'hero_death_prophet_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_death_prophet',
  },
  {
    id: 'hero_death_prophet_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.TOWER_KILLS,
    target: 5,
    heroName: 'npc_dota_hero_death_prophet',
  },
  {
    id: 'hero_doom_bringer_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 50,
    heroName: 'npc_dota_hero_doom_bringer',
  },
  {
    id: 'hero_doom_bringer_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_doom_bringer',
  },
  {
    id: 'hero_drow_ranger_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 550_000,
    heroName: 'npc_dota_hero_drow_ranger',
  },
  {
    id: 'hero_drow_ranger_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.TOWER_KILLS,
    target: 3,
    heroName: 'npc_dota_hero_drow_ranger',
  },
  {
    id: 'hero_earth_spirit_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 60,
    heroName: 'npc_dota_hero_earth_spirit',
  },
  {
    id: 'hero_earth_spirit_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 200_000,
    heroName: 'npc_dota_hero_earth_spirit',
  },
  {
    id: 'hero_elder_titan_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 400_000,
    heroName: 'npc_dota_hero_elder_titan',
  },
  {
    id: 'hero_elder_titan_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 200_000,
    heroName: 'npc_dota_hero_elder_titan',
  },
  {
    id: 'hero_ember_spirit_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_ember_spirit',
  },
  {
    id: 'hero_enchantress_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HEALING,
    target: 20_000,
    heroName: 'npc_dota_hero_enchantress',
  },
  {
    id: 'hero_enchantress_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 320_000,
    heroName: 'npc_dota_hero_enchantress',
  },
  {
    id: 'hero_faceless_void_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 480_000,
    heroName: 'npc_dota_hero_faceless_void',
  },
  {
    id: 'hero_faceless_void_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 220_000,
    heroName: 'npc_dota_hero_faceless_void',
  },
  {
    id: 'hero_grimstroke_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 70,
    heroName: 'npc_dota_hero_grimstroke',
  },
  {
    id: 'hero_grimstroke_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 50,
    heroName: 'npc_dota_hero_grimstroke',
  },
  {
    id: 'hero_gyrocopter_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 60,
    heroName: 'npc_dota_hero_gyrocopter',
  },
  {
    id: 'hero_gyrocopter_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 550_000,
    heroName: 'npc_dota_hero_gyrocopter',
  },
  {
    id: 'hero_huskar_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 480_000,
    heroName: 'npc_dota_hero_huskar',
  },
  {
    id: 'hero_huskar_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 200_000,
    heroName: 'npc_dota_hero_huskar',
  },
  {
    id: 'hero_invoker_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_invoker',
  },
  {
    id: 'hero_invoker_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 50,
    heroName: 'npc_dota_hero_invoker',
  },
  {
    id: 'hero_wisp_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HEALING,
    target: 80_000,
    heroName: 'npc_dota_hero_wisp',
  },
  {
    id: 'hero_wisp_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 40,
    heroName: 'npc_dota_hero_wisp',
  },
  {
    id: 'hero_jakiro_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 80,
    heroName: 'npc_dota_hero_jakiro',
  },
  {
    id: 'hero_jakiro_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 350_000,
    heroName: 'npc_dota_hero_jakiro',
  },
  {
    id: 'hero_keeper_of_the_light_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HEALING,
    target: 30_000,
    heroName: 'npc_dota_hero_keeper_of_the_light',
  },
  {
    id: 'hero_keeper_of_the_light_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 60,
    heroName: 'npc_dota_hero_keeper_of_the_light',
  },
  {
    id: 'hero_legion_commander_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_legion_commander',
  },
  {
    id: 'hero_legion_commander_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.KILLS,
    target: 40,
    heroName: 'npc_dota_hero_legion_commander',
  },
  {
    id: 'hero_leshrac_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_leshrac',
  },
  {
    id: 'hero_leshrac_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.TOWER_KILLS,
    target: 5,
    heroName: 'npc_dota_hero_leshrac',
  },
  {
    id: 'hero_lich_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 600_000,
    heroName: 'npc_dota_hero_lich',
  },
  {
    id: 'hero_lich_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 40,
    heroName: 'npc_dota_hero_lich',
  },
  {
    id: 'hero_life_stealer_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 480_000,
    heroName: 'npc_dota_hero_life_stealer',
  },
  {
    id: 'hero_life_stealer_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 200_000,
    heroName: 'npc_dota_hero_life_stealer',
  },
  {
    id: 'hero_lone_druid_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 40,
    heroName: 'npc_dota_hero_lone_druid',
  },
  {
    id: 'hero_lone_druid_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.TOWER_KILLS,
    target: 5,
    heroName: 'npc_dota_hero_lone_druid',
  },
  {
    id: 'hero_luna_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 40,
    heroName: 'npc_dota_hero_luna',
  },
  {
    id: 'hero_luna_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_luna',
  },
  {
    id: 'hero_lycan_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 480_000,
    heroName: 'npc_dota_hero_lycan',
  },
  {
    id: 'hero_lycan_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.TOWER_KILLS,
    target: 5,
    heroName: 'npc_dota_hero_lycan',
  },
  {
    id: 'hero_magnataur_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 80,
    heroName: 'npc_dota_hero_magnataur',
  },
  {
    id: 'hero_magnataur_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 60,
    heroName: 'npc_dota_hero_magnataur',
  },
  {
    id: 'hero_mars_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 60,
    heroName: 'npc_dota_hero_mars',
  },
  {
    id: 'hero_mars_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 480_000,
    heroName: 'npc_dota_hero_mars',
  },
  {
    id: 'hero_medusa_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 550_000,
    heroName: 'npc_dota_hero_medusa',
  },
  {
    id: 'hero_meepo_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 70,
    heroName: 'npc_dota_hero_meepo',
  },
  {
    id: 'hero_mirana_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 60,
    heroName: 'npc_dota_hero_mirana',
  },
  {
    id: 'hero_mirana_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_mirana',
  },
  {
    id: 'hero_morphling_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 60,
    heroName: 'npc_dota_hero_morphling',
  },
  {
    id: 'hero_morphling_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 550_000,
    heroName: 'npc_dota_hero_morphling',
  },
  {
    id: 'hero_monkey_king_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 50,
    heroName: 'npc_dota_hero_monkey_king',
  },
  {
    id: 'hero_monkey_king_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 480_000,
    heroName: 'npc_dota_hero_monkey_king',
  },
  {
    id: 'hero_naga_siren_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 80,
    heroName: 'npc_dota_hero_naga_siren',
  },
  {
    id: 'hero_naga_siren_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 480_000,
    heroName: 'npc_dota_hero_naga_siren',
  },
  {
    id: 'hero_furion_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_furion',
  },
  {
    id: 'hero_furion_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.TOWER_KILLS,
    target: 5,
    heroName: 'npc_dota_hero_furion',
  },
  {
    id: 'hero_night_stalker_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_night_stalker',
  },
  {
    id: 'hero_night_stalker_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 200_000,
    heroName: 'npc_dota_hero_night_stalker',
  },
  {
    id: 'hero_nyx_assassin_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 200,
    heroName: 'npc_dota_hero_nyx_assassin',
  },
  {
    id: 'hero_nyx_assassin_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 400_000,
    heroName: 'npc_dota_hero_nyx_assassin',
  },
  {
    id: 'hero_ogre_magi_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 90,
    heroName: 'npc_dota_hero_ogre_magi',
  },
  {
    id: 'hero_ogre_magi_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 350_000,
    heroName: 'npc_dota_hero_ogre_magi',
  },
  {
    id: 'hero_oracle_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HEALING,
    target: 80_000,
    heroName: 'npc_dota_hero_oracle',
  },
  {
    id: 'hero_oracle_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 70,
    heroName: 'npc_dota_hero_oracle',
  },
  {
    id: 'hero_obsidian_destroyer_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_obsidian_destroyer',
  },
  {
    id: 'hero_obsidian_destroyer_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.KILLS,
    target: 40,
    heroName: 'npc_dota_hero_obsidian_destroyer',
  },
  {
    id: 'hero_pangolier_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 120,
    heroName: 'npc_dota_hero_pangolier',
  },
  {
    id: 'hero_pangolier_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_pangolier',
  },
  {
    id: 'hero_phantom_lancer_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 240,
    heroName: 'npc_dota_hero_phantom_lancer',
  },
  {
    id: 'hero_phantom_lancer_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 450_000,
    heroName: 'npc_dota_hero_phantom_lancer',
  },
  {
    id: 'hero_puck_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 40,
    heroName: 'npc_dota_hero_puck',
  },
  {
    id: 'hero_puck_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 400_000,
    heroName: 'npc_dota_hero_puck',
  },
  {
    id: 'hero_pugna_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 400_000,
    heroName: 'npc_dota_hero_pugna',
  },
  {
    id: 'hero_queenofpain_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 550_000,
    heroName: 'npc_dota_hero_queenofpain',
  },
  {
    id: 'hero_queenofpain_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.KILLS,
    target: 40,
    heroName: 'npc_dota_hero_queenofpain',
  },
  {
    id: 'hero_razor_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 550_000,
    heroName: 'npc_dota_hero_razor',
  },
  {
    id: 'hero_razor_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 200_000,
    heroName: 'npc_dota_hero_razor',
  },
  {
    id: 'hero_riki_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 480_000,
    heroName: 'npc_dota_hero_riki',
  },
  {
    id: 'hero_riki_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.KILLS,
    target: 36,
    heroName: 'npc_dota_hero_riki',
  },
  {
    id: 'hero_rubick_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 60,
    heroName: 'npc_dota_hero_rubick',
  },
  {
    id: 'hero_rubick_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 70,
    heroName: 'npc_dota_hero_rubick',
  },
  {
    id: 'hero_sand_king_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 70,
    heroName: 'npc_dota_hero_sand_king',
  },
  {
    id: 'hero_sand_king_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 50,
    heroName: 'npc_dota_hero_sand_king',
  },
  {
    id: 'hero_shadow_demon_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 50,
    heroName: 'npc_dota_hero_shadow_demon',
  },
  {
    id: 'hero_skywrath_mage_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 800_000,
    heroName: 'npc_dota_hero_skywrath_mage',
  },
  {
    id: 'hero_slardar_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 100,
    heroName: 'npc_dota_hero_slardar',
  },
  {
    id: 'hero_slardar_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 200_000,
    heroName: 'npc_dota_hero_slardar',
  },
  {
    id: 'hero_slark_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_slark',
  },
  {
    id: 'hero_slark_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.KILLS,
    target: 40,
    heroName: 'npc_dota_hero_slark',
  },
  {
    id: 'hero_snapfire_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 350_000,
    heroName: 'npc_dota_hero_snapfire',
  },
  {
    id: 'hero_snapfire_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 40,
    heroName: 'npc_dota_hero_snapfire',
  },
  {
    id: 'hero_spectre_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 480_000,
    heroName: 'npc_dota_hero_spectre',
  },
  {
    id: 'hero_spectre_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 240_000,
    heroName: 'npc_dota_hero_spectre',
  },
  {
    id: 'hero_spirit_breaker_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 120,
    heroName: 'npc_dota_hero_spirit_breaker',
  },
  {
    id: 'hero_spirit_breaker_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 220_000,
    heroName: 'npc_dota_hero_spirit_breaker',
  },
  {
    id: 'hero_storm_spirit_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 550_000,
    heroName: 'npc_dota_hero_storm_spirit',
  },
  {
    id: 'hero_storm_spirit_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.KILLS,
    target: 40,
    heroName: 'npc_dota_hero_storm_spirit',
  },
  {
    id: 'hero_techies_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 600_000,
    heroName: 'npc_dota_hero_techies',
  },
  {
    id: 'hero_techies_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.KILLS,
    target: 32,
    heroName: 'npc_dota_hero_techies',
  },
  {
    id: 'hero_templar_assassin_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.KILLS,
    target: 40,
    heroName: 'npc_dota_hero_templar_assassin',
  },
  {
    id: 'hero_templar_assassin_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.TOWER_KILLS,
    target: 4,
    heroName: 'npc_dota_hero_templar_assassin',
  },
  {
    id: 'hero_terrorblade_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 550_000,
    heroName: 'npc_dota_hero_terrorblade',
  },
  {
    id: 'hero_terrorblade_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.TOWER_KILLS,
    target: 5,
    heroName: 'npc_dota_hero_terrorblade',
  },
  {
    id: 'hero_shredder_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 400_000,
    heroName: 'npc_dota_hero_shredder',
  },
  {
    id: 'hero_shredder_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 220_000,
    heroName: 'npc_dota_hero_shredder',
  },
  {
    id: 'hero_tinker_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_tinker',
  },
  {
    id: 'hero_tinker_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 60,
    heroName: 'npc_dota_hero_tinker',
  },
  {
    id: 'hero_tiny_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 40,
    heroName: 'npc_dota_hero_tiny',
  },
  {
    id: 'hero_tiny_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_tiny',
  },
  {
    id: 'hero_treant_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HEALING,
    target: 30_000,
    heroName: 'npc_dota_hero_treant',
  },
  {
    id: 'hero_treant_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 50,
    heroName: 'npc_dota_hero_treant',
  },
  {
    id: 'hero_troll_warlord_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 550_000,
    heroName: 'npc_dota_hero_troll_warlord',
  },
  {
    id: 'hero_troll_warlord_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.TOWER_KILLS,
    target: 5,
    heroName: 'npc_dota_hero_troll_warlord',
  },
  {
    id: 'hero_tusk_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 70,
    heroName: 'npc_dota_hero_tusk',
  },
  {
    id: 'hero_tusk_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.ASSISTS,
    target: 50,
    heroName: 'npc_dota_hero_tusk',
  },
  {
    id: 'hero_abyssal_underlord_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 350_000,
    heroName: 'npc_dota_hero_abyssal_underlord',
  },
  {
    id: 'hero_abyssal_underlord_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 220_000,
    heroName: 'npc_dota_hero_abyssal_underlord',
  },
  {
    id: 'hero_undying_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 350_000,
    heroName: 'npc_dota_hero_undying',
  },
  {
    id: 'hero_ursa_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 480_000,
    heroName: 'npc_dota_hero_ursa',
  },
  {
    id: 'hero_ursa_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.KILLS,
    target: 40,
    heroName: 'npc_dota_hero_ursa',
  },
  {
    id: 'hero_vengefulspirit_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 60,
    heroName: 'npc_dota_hero_vengefulspirit',
  },
  {
    id: 'hero_vengefulspirit_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 350_000,
    heroName: 'npc_dota_hero_vengefulspirit',
  },
  {
    id: 'hero_visage_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_visage',
  },
  {
    id: 'hero_visage_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.KILLS,
    target: 40,
    heroName: 'npc_dota_hero_visage',
  },
  {
    id: 'hero_void_spirit_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_void_spirit',
  },
  {
    id: 'hero_void_spirit_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.KILLS,
    target: 40,
    heroName: 'npc_dota_hero_void_spirit',
  },
  {
    id: 'hero_weaver_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 480_000,
    heroName: 'npc_dota_hero_weaver',
  },
  {
    id: 'hero_weaver_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.KILLS,
    target: 40,
    heroName: 'npc_dota_hero_weaver',
  },
  {
    id: 'hero_winter_wyvern_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HEALING,
    target: 10_000,
    heroName: 'npc_dota_hero_winter_wyvern',
  },
  {
    id: 'hero_winter_wyvern_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 350_000,
    heroName: 'npc_dota_hero_winter_wyvern',
  },
  {
    id: 'hero_skeleton_king_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 60,
    heroName: 'npc_dota_hero_skeleton_king',
  },
  {
    id: 'hero_skeleton_king_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 480_000,
    heroName: 'npc_dota_hero_skeleton_king',
  },
  {
    id: 'hero_hoodwink_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 70,
    heroName: 'npc_dota_hero_hoodwink',
  },
  {
    id: 'hero_hoodwink_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 350_000,
    heroName: 'npc_dota_hero_hoodwink',
  },
  {
    id: 'hero_dawnbreaker_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HEALING,
    target: 30_000,
    heroName: 'npc_dota_hero_dawnbreaker',
  },
  {
    id: 'hero_dawnbreaker_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 480_000,
    heroName: 'npc_dota_hero_dawnbreaker',
  },
  {
    id: 'hero_marci_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 50,
    heroName: 'npc_dota_hero_marci',
  },
  {
    id: 'hero_marci_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 480_000,
    heroName: 'npc_dota_hero_marci',
  },
  {
    id: 'hero_primal_beast_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 100,
    heroName: 'npc_dota_hero_primal_beast',
  },
  {
    id: 'hero_primal_beast_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.DAMAGE_TAKEN,
    target: 240_000,
    heroName: 'npc_dota_hero_primal_beast',
  },
  {
    id: 'hero_muerta_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 500_000,
    heroName: 'npc_dota_hero_muerta',
  },
  {
    id: 'hero_muerta_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.KILLS,
    target: 40,
    heroName: 'npc_dota_hero_muerta',
  },
  {
    id: 'hero_ringmaster_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 50,
    heroName: 'npc_dota_hero_ringmaster',
  },
  {
    id: 'hero_ringmaster_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 350_000,
    heroName: 'npc_dota_hero_ringmaster',
  },
  {
    id: 'hero_kez_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HERO_DAMAGE,
    target: 480_000,
    heroName: 'npc_dota_hero_kez',
  },
  {
    id: 'hero_kez_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.KILLS,
    target: 40,
    heroName: 'npc_dota_hero_kez',
  },
  {
    id: 'hero_largo_1',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.STUN_DURATION,
    target: 50,
    heroName: 'npc_dota_hero_largo',
  },
  {
    id: 'hero_largo_2',
    scope: TaskScope.PERSONAL_HERO,
    metric: TaskMetric.HEALING,
    target: 20_000,
    heroName: 'npc_dota_hero_largo',
  },
];
