import React from 'react';
import '@/styles/globals.css';

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;