CREATE TABLE IF NOT EXISTS `${PROJECT_ID}.${DATASET}.game_end_players` (
  game_id STRING NOT NULL,
  match_id STRING,
  ended_at TIMESTAMP NOT NULL,
  version STRING,
  difficulty INT64,
  server_type STRING,
  route STRING,
  country STRING,
  player_count INT64,
  winner_team_id INT64,
  game_time_msec INT64,
  game_options STRUCT<
    multiplier_radiant FLOAT64,
    multiplier_dire FLOAT64,
    player_number_radiant INT64,
    player_number_dire INT64,
    tower_power_pct INT64,
    respawn_time_pct INT64
  >,
  steam_id INT64 NOT NULL,
  team_id INT64,
  hero_name STRING,
  is_winner BOOL,
  is_disconnected BOOL,
  level INT64,
  score INT64,
  battle_points INT64,
  daily_task_point INT64,
  awaken INT64,
  kills INT64,
  deaths INT64,
  assists INT64,
  last_hits INT64,
  hero_damage INT64,
  damage_taken INT64,
  healing INT64,
  tower_kills INT64,
  total_gold_earned INT64,
  stuns FLOAT64,
  roshan_kills INT64,
  strength INT64,
  agility INT64,
  intellect INT64,
  items ARRAY<STRING>,
  neutral_item STRING,
  neutral_passive_item STRING,
  abilities ARRAY<STRING>,
  raw JSON
)
PARTITION BY DATE(ended_at)
CLUSTER BY steam_id, difficulty, hero_name;
