name: Create Release PR
on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Reset promotion branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop

      - name: Check if PR exist_pr_number
        id: check_pr
        run: |
          pr_exists=$(gh pr list --base main --head develop --json number -q '.[0].number')
          echo pr_exists=$pr_exists >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: cpr
        if: steps.check_pr.outputs.pr_exists == ''
        uses: peter-evans/create-pull-request@v7
        with:
          title: Release
          branch: develop
          base: main
          reviewers: windybirth
          labels: release
          draft: true

      - name: Ready Pull Request
        if: steps.check_pr.outputs.pr_exists == ''
        run: gh pr ready ${{ steps.cpr.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.WINDY_PR_PAT }}

      - name: Enable Pull Request Automerge
        if: steps.check_pr.outputs.pr_exists == ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.WINDY_PR_PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge
